spring:
  application:
    name: taco-cloud

  main:
    banner-mode: off

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: '*'
